---
- name: make sure to become true
  include: ensure_become.yml

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install postgres server on RedHat family
  yum: name=postgresql-server state=present
  when: ansible_os_family == 'RedHat'

- name: install postgres server on Debian family
  apt: name=postgresql-server state=present
  when: ansible_os_family == 'Debian'
