---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install postgres server on RedHat family
  yum: name=postgresql-server state=present
  when: ansible_os_family == 'RedHat'

- name: install postgres server on Debian family
  apt: name=postgresql-server state=present
  when: ansible_os_family == 'Debian'

- name: check if the postgres_data_directory is empty
  command: "ls {{ postgres_data_directory }}"
  register: postgres_data_directory_contents

- name: initialize
  shell: "postgresql-setup initdb"
  become: true
  when: postgres_data_directory_contents.stdout == ""

- name: enable and start postgres service
  service:
    name: postgresql
    enabled: yes
    state: started
  become: true
